name: .NET Build & Test

on:
  push:
    branches: [ main ]
    paths: [ 'HuTao.NET.Tests/**', 'HuTao.NET.sln', '.github/workflows/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'HuTao.NET.Tests/**', 'HuTao.NET.sln', '.github/workflows/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build all projects
        run: dotnet build --no-restore --configuration Release

      - name: Run tests (failures allowed)
        run: |
          dotnet test --no-build --configuration Release || true 